### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by KaySackey** [okeuday/varpool#1]
Do you have any example code on how to use this library?

**Comment by okeuday** [comment]
The edoc output is generated from the source code and put into the doc directory.  However, the main basic example is in the eunit test at https://github.com/okeuday/varpool/blob/master/test/varpool_test_server.erl#L88-L127 .  The options available are listed at https://github.com/okeuday/varpool/blob/master/src/varpool.erl#L98-L104 if you want to understand the defaults being used by the eunit test.
